### PR TITLE
Only look for socket connections to X server.

### LINKED ISSUE #782: [ERROR]Cannot access secondary GPU - error: X unresponsive after 10 seconds - aborting
optiruns fail to start any application.
The secondary Xorg starts properly and works: (after some changes in config) on second monitor I see running xterm `DISPLAY=:8 xterm`

```
optirun -vvv glxgears --info
[ 5520.303586] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 5520.303888] [INFO]Configured driver: nvidia
[ 5520.304088] [DEBUG]optirun version 3.2.1 starting...
[ 5520.304106] [DEBUG]Active configuration:
[ 5520.304111] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 5520.304118] [DEBUG] X display: :8
[ 5520.304125] [DEBUG] LD_LIBRARY_PATH: /usr/lib/nvidia:/usr/lib32/nvidia
[ 5520.304132] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 5520.304143] [DEBUG] Accel/display bridge: primus
[ 5520.304151] [DEBUG] VGL Compression: proxy
[ 5520.304160] [DEBUG] VGLrun extra options: 
[ 5520.304170] [DEBUG] Primus LD Path: /usr/lib/primus:/usr/lib32/primus
[ 5647.723198] [INFO]Response: No - error: X unresponsive after 10 seconds - aborting

[ 5647.723208] [ERROR]Cannot access secondary GPU - error: X unresponsive after 10 seconds - aborting

[ 5647.723213] [DEBUG]Socket closed.
[ 5647.723229] [ERROR]Aborting because fallback start is disabled.
[ 5647.723231] [DEBUG]Killing all remaining processes.
```

```
Distro: ArchLinux
Kernel: Linux travnick-pc 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux
Manufacturer and model: 
Gigabyte Technology Co., Ltd.
baseboard-product-name: Z97X-SOC Force
baseboard-version     : x.x
system-manufacturer   : Gigabyte Technology Co., Ltd.
system-product-name   : Z97X-SOC Force
system-version        : To be filled by O.E.M.
bios-vendor           : American Megatrends Inc.
bios-version          : F7
bios-release-date     : 04/21/2015

optirun -V
optirun (Bumblebee) 3.2.1
Copyright (C) 2011 The Bumblebee Project
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

### PR DESCRIPTION
**Pull request by westernmagic**
`XOpenDisplay` tries all protocolls in turn (socket, IPv4, IPv6) [1]. This can lead to delays and timeouts, especially on systems with incomplete `/etc/hosts` (eg. missing `localhost` → `127.0.0.1`), due to the fact that the hostname has to be resolved.

Since we start the X server not accepting TCP connections, we can pass the protocoll to `XOpenDisplay`.

Closes #782.

[1] http://xwindow.angelfire.com/page2.html

### CODE REVIEW

**Comment by ryanmisturak** [comment]
Please merge this.  Spent the better part of two days trying to figure out why Bumblebee seemed to work only 20% of the time before finding this.  For any other person looking for a workaround, adding 
`127.0.0.1   localhost` to `/etc/hosts` as alluded to by @westernmagic does seem to work.

File: src/bbsecondary.c [hunk 1]
```diff
@@ -184,8 +184,10 @@ bool start_secondary(bool need_secondary) {
   //check if X is available, for maximum 10 seconds.
   time_t xtimer = time(0);
   Display * xdisp = 0;
+  char unix_x_display[5 + sizeof(bb_config.x_display)] = "unix/";
+  strcat(unix_x_display, bb_config.x_display);
```
Comment (Lekensteyn) [inline src/bbsecondary.c]: `sizeof(bb_config.c_display)` is not correct, it gives the size of a pointer. Also `strcat` should not be used due to the risk of a buffer overrun.

What about:
```c
char unix_x_display[16];
snprintf(unix_x_display, sizeof(unix_x_display), "unix/%s", bb_config.x_display);
```

Alternatively, you could set `g_strdup_printf("unix/%s", bb_config.x_display)`, but that needs to be freed afterwards.

**Comment by Lekensteyn** [comment]
Thanks!
